[Settings]
; Kill MSI Afterburner on startup (or just manually remove it from your Startup applications)
KillAfterburnerOnStart=1
; Milliseconds between checks (default 5000)
CheckInterval=5000
; Seconds to wait for RTSS to start with Afterburner
WaitForRTSSToOpen=10
; 1 = start RTSS if Afterburner didn't, 0 do not start RTSS forcefully
ForceLaunchRTSS=1
; Close requests Kelvin sends before giving up on MSI Afterburner
MaxCloseAttempts=6

[Paths]
; Leave blank so Kelvin does the work for you
Afterburner=
RTSS=

[Targets]
; One exe file per line
; To check your game's specific exe name, open Task Manager and go to details to search for your game
1=notepad.exe